{
  "name": "SemanticModel",
  "compatibilityLevel": 1500,
  "model": {
    "culture": "ru-RU",
    "dataSources": [
      {
        "type": "structured",
        "name": "SQL/belchenkotestserver1 database windows net;belchenkosqlpool1",
        "connectionDetails": {
          "protocol": "tds",
          "address": {
            "server": "belchenkotestserver1.database.windows.net",
            "database": "belchenkosqlpool1"
          },
          "authentication": null,
          "query": null
        },
        "options": {},
        "credential": {
          "AuthenticationKind": "UsernamePassword",
          "Username": "belchenko",
          "EncryptConnection": true
        }
      }
    ],
    "tables": [
      {
        "name": "DimDate",
        "columns": [
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          },
          {
            "name": "Date",
            "dataType": "dateTime",
            "sourceColumn": "FullDateAlternateKey"
          },
          {
            "name": "DayNumberOfWeek",
            "dataType": "int64",
            "sourceColumn": "DayNumberOfWeek"
          },
          {
            "name": "EnglishDayNameOfWeek",
            "dataType": "string",
            "sourceColumn": "EnglishDayNameOfWeek"
          },
          {
            "name": "DayNumberOfMonth",
            "dataType": "int64",
            "sourceColumn": "DayNumberOfMonth"
          },
          {
            "name": "DayNumberOfYear",
            "dataType": "int64",
            "sourceColumn": "DayNumberOfYear"
          },
          {
            "name": "WeekNumberOfYear",
            "dataType": "int64",
            "sourceColumn": "WeekNumberOfYear"
          },
          {
            "name": "EnglishMonthName",
            "dataType": "string",
            "sourceColumn": "EnglishMonthName"
          },
          {
            "name": "MonthNumberOfYear",
            "dataType": "int64",
            "sourceColumn": "MonthNumberOfYear"
          },
          {
            "name": "CalendarQuarter",
            "dataType": "int64",
            "sourceColumn": "CalendarQuarter"
          },
          {
            "name": "CalendarYear",
            "dataType": "int64",
            "sourceColumn": "CalendarYear"
          },
          {
            "name": "CalendarSemester",
            "dataType": "int64",
            "sourceColumn": "CalendarSemester"
          },
          {
            "name": "FiscalQuarter",
            "dataType": "int64",
            "sourceColumn": "FiscalQuarter"
          },
          {
            "name": "FiscalYear",
            "dataType": "int64",
            "sourceColumn": "FiscalYear"
          },
          {
            "name": "FiscalSemester",
            "dataType": "int64",
            "sourceColumn": "FiscalSemester"
          },
          {
            "type": "calculated",
            "name": "MonthCalendar",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "RIGHT(\" \" & FORMAT([MonthNumberOfYear],\"#0\"), 2) & \" - \" & [EnglishMonthName]  "
          },
          {
            "type": "calculated",
            "name": "DayOfWeek ",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "RIGHT(\" \" & FORMAT([DayNumberOfWeek],\"#0\"), 2) & \" - \" & [EnglishDayNameOfWeek]  "
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/belchenkotestserver1 database windows net;belchenkosqlpool1\",",
                "    dbo_DimDate = Source{[Schema=\"dbo\",Item=\"DimDate\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(dbo_DimDate,{\"SpanishDayNameOfWeek\", \"FrenchDayNameOfWeek\", \"SpanishMonthName\", \"FrenchMonthName\"})",
                "in",
                "    #\"Removed Columns\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "DaysCurrentQuarterToDate",
            "expression": "COUNTROWS( DATESQTD( 'DimDate'[Date])) "
          },
          {
            "name": "DaysInCurrentQuarter",
            "expression": "COUNTROWS( DATESBETWEEN( 'DimDate'[Date], STARTOFQUARTER( LASTDATE('DimDate'[Date])), ENDOFQUARTER('DimDate'[Date])))"
          }
        ]
      },
      {
        "name": "DimCustomer",
        "columns": [
          {
            "name": "CustomerKey",
            "dataType": "int64",
            "sourceColumn": "CustomerKey"
          },
          {
            "name": "GeographyKey",
            "dataType": "int64",
            "sourceColumn": "GeographyKey"
          },
          {
            "name": "CustomerAlternateKey",
            "dataType": "string",
            "sourceColumn": "CustomerAlternateKey"
          },
          {
            "name": "Title",
            "dataType": "string",
            "sourceColumn": "Title"
          },
          {
            "name": "FirstName",
            "dataType": "string",
            "sourceColumn": "FirstName"
          },
          {
            "name": "MiddleName",
            "dataType": "string",
            "sourceColumn": "MiddleName"
          },
          {
            "name": "LastName",
            "dataType": "string",
            "sourceColumn": "LastName"
          },
          {
            "name": "NameStyle",
            "dataType": "boolean",
            "sourceColumn": "NameStyle"
          },
          {
            "name": "BirthDate",
            "dataType": "dateTime",
            "sourceColumn": "BirthDate"
          },
          {
            "name": "MaritalStatus",
            "dataType": "string",
            "sourceColumn": "MaritalStatus"
          },
          {
            "name": "Suffix",
            "dataType": "string",
            "sourceColumn": "Suffix"
          },
          {
            "name": "Gender",
            "dataType": "string",
            "sourceColumn": "Gender"
          },
          {
            "name": "EmailAddress",
            "dataType": "string",
            "sourceColumn": "EmailAddress"
          },
          {
            "name": "YearlyIncome",
            "dataType": "decimal",
            "sourceColumn": "YearlyIncome"
          },
          {
            "name": "TotalChildren",
            "dataType": "int64",
            "sourceColumn": "TotalChildren"
          },
          {
            "name": "NumberChildrenAtHome",
            "dataType": "int64",
            "sourceColumn": "NumberChildrenAtHome"
          },
          {
            "name": "EnglishEducation",
            "dataType": "string",
            "sourceColumn": "EnglishEducation"
          },
          {
            "name": "EnglishOccupation",
            "dataType": "string",
            "sourceColumn": "EnglishOccupation"
          },
          {
            "name": "HouseOwnerFlag",
            "dataType": "string",
            "sourceColumn": "HouseOwnerFlag"
          },
          {
            "name": "NumberCarsOwned",
            "dataType": "int64",
            "sourceColumn": "NumberCarsOwned"
          },
          {
            "name": "AddressLine1",
            "dataType": "string",
            "sourceColumn": "AddressLine1"
          },
          {
            "name": "AddressLine2",
            "dataType": "string",
            "sourceColumn": "AddressLine2"
          },
          {
            "name": "Phone",
            "dataType": "string",
            "sourceColumn": "Phone"
          },
          {
            "name": "DateFirstPurchase",
            "dataType": "dateTime",
            "sourceColumn": "DateFirstPurchase"
          },
          {
            "name": "CommuteDistance",
            "dataType": "string",
            "sourceColumn": "CommuteDistance"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/belchenkotestserver1 database windows net;belchenkosqlpool1\",",
                "    dbo_DimCustomer = Source{[Schema=\"dbo\",Item=\"DimCustomer\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(dbo_DimCustomer,{\"SpanishEducation\", \"FrenchEducation\", \"SpanishOccupation\", \"FrenchOccupation\"})",
                "in",
                "    #\"Removed Columns\""
              ]
            }
          }
        ]
      },
      {
        "name": "DimGeography",
        "columns": [
          {
            "name": "GeographyKey",
            "dataType": "int64",
            "sourceColumn": "GeographyKey"
          },
          {
            "name": "City",
            "dataType": "string",
            "sourceColumn": "City"
          },
          {
            "name": "StateProvinceCode",
            "dataType": "string",
            "sourceColumn": "StateProvinceCode"
          },
          {
            "name": "StateProvinceName",
            "dataType": "string",
            "sourceColumn": "StateProvinceName"
          },
          {
            "name": "CountryRegionCode",
            "dataType": "string",
            "sourceColumn": "CountryRegionCode"
          },
          {
            "name": "EnglishCountryRegionName",
            "dataType": "string",
            "sourceColumn": "EnglishCountryRegionName"
          },
          {
            "name": "PostalCode",
            "dataType": "string",
            "sourceColumn": "PostalCode"
          },
          {
            "name": "SalesTerritoryKey",
            "dataType": "int64",
            "sourceColumn": "SalesTerritoryKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/belchenkotestserver1 database windows net;belchenkosqlpool1\",",
                "    dbo_DimGeography = Source{[Schema=\"dbo\",Item=\"DimGeography\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(dbo_DimGeography,{\"SpanishCountryRegionName\", \"FrenchCountryRegionName\"})",
                "in",
                "    #\"Removed Columns\""
              ]
            }
          }
        ]
      },
      {
        "name": "DimProduct",
        "columns": [
          {
            "name": "ProductKey",
            "dataType": "int64",
            "sourceColumn": "ProductKey"
          },
          {
            "name": "ProductAlternateKey",
            "dataType": "string",
            "sourceColumn": "ProductAlternateKey"
          },
          {
            "name": "ProductSubcategoryKey",
            "dataType": "int64",
            "sourceColumn": "ProductSubcategoryKey"
          },
          {
            "name": "WeightUnitMeasureCode",
            "dataType": "string",
            "sourceColumn": "WeightUnitMeasureCode"
          },
          {
            "name": "SizeUnitMeasureCode",
            "dataType": "string",
            "sourceColumn": "SizeUnitMeasureCode"
          },
          {
            "name": "EnglishProductName",
            "dataType": "string",
            "sourceColumn": "EnglishProductName"
          },
          {
            "name": "SpanishProductName",
            "dataType": "string",
            "sourceColumn": "SpanishProductName"
          },
          {
            "name": "FrenchProductName",
            "dataType": "string",
            "sourceColumn": "FrenchProductName"
          },
          {
            "name": "StandardCost",
            "dataType": "decimal",
            "sourceColumn": "StandardCost"
          },
          {
            "name": "FinishedGoodsFlag",
            "dataType": "boolean",
            "sourceColumn": "FinishedGoodsFlag"
          },
          {
            "name": "Color",
            "dataType": "string",
            "sourceColumn": "Color"
          },
          {
            "name": "SafetyStockLevel",
            "dataType": "int64",
            "sourceColumn": "SafetyStockLevel"
          },
          {
            "name": "ReorderPoint",
            "dataType": "int64",
            "sourceColumn": "ReorderPoint"
          },
          {
            "name": "ListPrice",
            "dataType": "decimal",
            "sourceColumn": "ListPrice"
          },
          {
            "name": "Size",
            "dataType": "string",
            "sourceColumn": "Size"
          },
          {
            "name": "SizeRange",
            "dataType": "string",
            "sourceColumn": "SizeRange"
          },
          {
            "name": "Weight",
            "dataType": "double",
            "sourceColumn": "Weight"
          },
          {
            "name": "DaysToManufacture",
            "dataType": "int64",
            "sourceColumn": "DaysToManufacture"
          },
          {
            "name": "ProductLine",
            "dataType": "string",
            "sourceColumn": "ProductLine"
          },
          {
            "name": "DealerPrice",
            "dataType": "decimal",
            "sourceColumn": "DealerPrice"
          },
          {
            "name": "Class",
            "dataType": "string",
            "sourceColumn": "Class"
          },
          {
            "name": "Style",
            "dataType": "string",
            "sourceColumn": "Style"
          },
          {
            "name": "ModelName",
            "dataType": "string",
            "sourceColumn": "ModelName"
          },
          {
            "name": "EnglishDescription",
            "dataType": "string",
            "sourceColumn": "EnglishDescription"
          },
          {
            "name": "StartDate",
            "dataType": "dateTime",
            "sourceColumn": "StartDate"
          },
          {
            "name": "EndDate",
            "dataType": "dateTime",
            "sourceColumn": "EndDate"
          },
          {
            "name": "Status",
            "dataType": "string",
            "sourceColumn": "Status"
          },
          {
            "type": "calculated",
            "name": "ProductSubcategoryName",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "RELATED('DimProductSubcategory'[EnglishProductSubcategoryName]) "
          },
          {
            "type": "calculated",
            "name": "ProductCategoryName",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "RELATED('DimProductCategory'[EnglishProductCategoryName]) "
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/belchenkotestserver1 database windows net;belchenkosqlpool1\",",
                "    dbo_DimProduct = Source{[Schema=\"dbo\",Item=\"DimProduct\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(dbo_DimProduct,{\"FrenchDescription\", \"ChineseDescription\", \"ArabicDescription\", \"HebrewDescription\", \"ThaiDescription\", \"GermanDescription\", \"JapaneseDescription\", \"TurkishDescription\"})",
                "in",
                "    #\"Removed Columns\""
              ]
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Category",
            "levels": [
              {
                "name": "Category",
                "ordinal": 0,
                "column": "ProductCategoryName"
              },
              {
                "name": "Subcategory",
                "ordinal": 1,
                "column": "ProductSubcategoryName"
              },
              {
                "name": "Model",
                "ordinal": 2,
                "column": "ModelName"
              },
              {
                "name": "Product",
                "ordinal": 3,
                "column": "EnglishProductName"
              }
            ]
          }
        ]
      },
      {
        "name": "DimProductCategory",
        "columns": [
          {
            "name": "ProductCategoryKey",
            "dataType": "int64",
            "sourceColumn": "ProductCategoryKey"
          },
          {
            "name": "ProductCategoryAlternateKey",
            "dataType": "int64",
            "sourceColumn": "ProductCategoryAlternateKey"
          },
          {
            "name": "EnglishProductCategoryName",
            "dataType": "string",
            "sourceColumn": "EnglishProductCategoryName"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/belchenkotestserver1 database windows net;belchenkosqlpool1\",",
                "    dbo_DimProductCategory = Source{[Schema=\"dbo\",Item=\"DimProductCategory\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(dbo_DimProductCategory,{\"SpanishProductCategoryName\", \"FrenchProductCategoryName\"})",
                "in",
                "    #\"Removed Columns\""
              ]
            }
          }
        ]
      },
      {
        "name": "DimProductSubcategory",
        "columns": [
          {
            "name": "ProductSubcategoryKey",
            "dataType": "int64",
            "sourceColumn": "ProductSubcategoryKey"
          },
          {
            "name": "ProductSubcategoryAlternateKey",
            "dataType": "int64",
            "sourceColumn": "ProductSubcategoryAlternateKey"
          },
          {
            "name": "EnglishProductSubcategoryName",
            "dataType": "string",
            "sourceColumn": "EnglishProductSubcategoryName"
          },
          {
            "name": "ProductCategoryKey",
            "dataType": "int64",
            "sourceColumn": "ProductCategoryKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/belchenkotestserver1 database windows net;belchenkosqlpool1\",",
                "    dbo_DimProductSubcategory = Source{[Schema=\"dbo\",Item=\"DimProductSubcategory\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(dbo_DimProductSubcategory,{\"SpanishProductSubcategoryName\", \"FrenchProductSubcategoryName\"})",
                "in",
                "    #\"Removed Columns\""
              ]
            }
          }
        ]
      },
      {
        "name": "FactInternetSales",
        "columns": [
          {
            "name": "ProductKey",
            "dataType": "int64",
            "sourceColumn": "ProductKey"
          },
          {
            "name": "OrderDateKey",
            "dataType": "int64",
            "sourceColumn": "OrderDateKey"
          },
          {
            "name": "DueDateKey",
            "dataType": "int64",
            "sourceColumn": "DueDateKey"
          },
          {
            "name": "ShipDateKey",
            "dataType": "int64",
            "sourceColumn": "ShipDateKey"
          },
          {
            "name": "CustomerKey",
            "dataType": "int64",
            "sourceColumn": "CustomerKey"
          },
          {
            "name": "PromotionKey",
            "dataType": "int64",
            "sourceColumn": "PromotionKey"
          },
          {
            "name": "CurrencyKey",
            "dataType": "int64",
            "sourceColumn": "CurrencyKey"
          },
          {
            "name": "SalesTerritoryKey",
            "dataType": "int64",
            "sourceColumn": "SalesTerritoryKey"
          },
          {
            "name": "SalesOrderNumber",
            "dataType": "string",
            "sourceColumn": "SalesOrderNumber"
          },
          {
            "name": "SalesOrderLineNumber",
            "dataType": "int64",
            "sourceColumn": "SalesOrderLineNumber"
          },
          {
            "name": "RevisionNumber",
            "dataType": "int64",
            "sourceColumn": "RevisionNumber"
          },
          {
            "name": "OrderQuantity",
            "dataType": "int64",
            "sourceColumn": "OrderQuantity"
          },
          {
            "name": "UnitPrice",
            "dataType": "decimal",
            "sourceColumn": "UnitPrice"
          },
          {
            "name": "ExtendedAmount",
            "dataType": "decimal",
            "sourceColumn": "ExtendedAmount"
          },
          {
            "name": "UnitPriceDiscountPct",
            "dataType": "double",
            "sourceColumn": "UnitPriceDiscountPct"
          },
          {
            "name": "DiscountAmount",
            "dataType": "double",
            "sourceColumn": "DiscountAmount"
          },
          {
            "name": "ProductStandardCost",
            "dataType": "decimal",
            "sourceColumn": "ProductStandardCost"
          },
          {
            "name": "TotalProductCost",
            "dataType": "decimal",
            "sourceColumn": "TotalProductCost"
          },
          {
            "name": "SalesAmount",
            "dataType": "decimal",
            "sourceColumn": "SalesAmount"
          },
          {
            "name": "TaxAmt",
            "dataType": "decimal",
            "sourceColumn": "TaxAmt"
          },
          {
            "name": "Freight",
            "dataType": "decimal",
            "sourceColumn": "Freight"
          },
          {
            "name": "CarrierTrackingNumber",
            "dataType": "string",
            "sourceColumn": "CarrierTrackingNumber"
          },
          {
            "name": "CustomerPONumber",
            "dataType": "string",
            "sourceColumn": "CustomerPONumber"
          },
          {
            "type": "calculated",
            "name": "Margin",
            "dataType": "decimal",
            "isDataTypeInferred": true,
            "expression": "[SalesAmount]-[TotalProductCost]",
            "formatString": "#,0.00 \"₽\";-#,0.00 \"₽\";#,0.00 \"₽\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1049\" DisplayName=\"₽ Russian (Russia)\" Symbol=\"₽\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/belchenkotestserver1 database windows net;belchenkosqlpool1\",",
                "    dbo_FactInternetSales = Source{[Schema=\"dbo\",Item=\"FactInternetSales\"]}[Data]",
                "in",
                "    dbo_FactInternetSales"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "InternetDistinctCountSalesOrder",
            "expression": "DISTINCTCOUNT([SalesOrderNumber])"
          },
          {
            "name": "InternetOrderLinesCount",
            "expression": "COUNTA([SalesOrderLineNumber])"
          },
          {
            "name": "InternetTotalUnits",
            "expression": "SUM([OrderQuantity])"
          },
          {
            "name": "InternetTotalDiscountAmount",
            "expression": "SUM([DiscountAmount])"
          },
          {
            "name": "InternetTotalProductCost",
            "expression": "SUM([TotalProductCost])",
            "formatString": "#,0.00 \"₽\";-#,0.00 \"₽\";#,0.00 \"₽\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1049\" DisplayName=\"₽ Russian (Russia)\" Symbol=\"₽\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "InternetTotalSales",
            "expression": "SUM([SalesAmount])",
            "formatString": "#,0.00 \"₽\";-#,0.00 \"₽\";#,0.00 \"₽\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1049\" DisplayName=\"₽ Russian (Russia)\" Symbol=\"₽\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "InternetTotalMargin",
            "expression": "SUM([Margin])",
            "formatString": "#,0.00 \"₽\";-#,0.00 \"₽\";#,0.00 \"₽\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1049\" DisplayName=\"₽ Russian (Russia)\" Symbol=\"₽\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "InternetTotalTaxAmt",
            "expression": "SUM([TaxAmt])",
            "formatString": "#,0.00 \"₽\";-#,0.00 \"₽\";#,0.00 \"₽\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1049\" DisplayName=\"₽ Russian (Russia)\" Symbol=\"₽\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "InternetTotalFreight",
            "expression": "SUM([Freight])",
            "formatString": "#,0.00 \"₽\";-#,0.00 \"₽\";#,0.00 \"₽\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1049\" DisplayName=\"₽ Russian (Russia)\" Symbol=\"₽\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "InternetPreviousQuarterMargin",
            "expression": "CALCULATE([InternetTotalMargin],PREVIOUSQUARTER('DimDate'[Date]))"
          },
          {
            "name": "InternetPreviousQuarterMarginProportionToQTD",
            "expression": "[InternetPreviousQuarterMargin]*([DaysCurrentQuarterToDate]/[DaysInCurrentQuarter])"
          },
          {
            "name": "InternetCurrentQuarterMargin",
            "expression": "TOTALQTD([InternetTotalMargin],'DimDate'[Date])"
          },
          {
            "name": "InternetPreviousQuarterSales",
            "expression": [
              "CALCULATE([InternetTotalSales],PREVIOUSQUARTER('DimDate'[Date]))",
              ""
            ]
          },
          {
            "name": "InternetCurrentQuarterSales",
            "expression": "TOTALQTD([InternetTotalSales],'DimDate'[Date])"
          },
          {
            "name": "InternetPreviousQuarterSalesProportionToQTD",
            "expression": "[InternetPreviousQuarterSales]*([DaysCurrentQuarterToDate]/[DaysInCurrentQuarter])"
          },
          {
            "name": "InternetCurrentQuarterSalesPerformance",
            "expression": "IF([InternetPreviousQuarterSalesProportionToQTD]<>0,([InternetCurrentQuarterSales]-[InternetPreviousQuarterSalesProportionToQTD])/[InternetPreviousQuarterSalesProportionToQTD],BLANK())",
            "kpi": {
              "targetExpression": "1,1",
              "statusGraphic": "Shapes",
              "statusExpression": [
                "var x='FactInternetSales'[InternetCurrentQuarterSalesPerformance] return",
                "            if(ISBLANK(x),BLANK(),",
                "                    If(x<1,-1,",
                "\t                If(x<1.07,0,1)",
                "                )",
                "            )",
                "            "
              ],
              "annotations": [
                {
                  "name": "GoalType",
                  "value": "StaticValue"
                },
                {
                  "name": "KpiStatusType",
                  "value": "Linear"
                },
                {
                  "name": "KpiThresholdType",
                  "value": "Absolute"
                },
                {
                  "name": "KpiThresholdOrdering",
                  "value": "Ascending"
                },
                {
                  "name": "KpiThresholdCount",
                  "value": "2"
                },
                {
                  "name": "KpiThreshold_0",
                  "value": "1"
                },
                {
                  "name": "KpiThreshold_1",
                  "value": "1.07"
                }
              ]
            }
          },
          {
            "name": "InternetCurrentQuarterMarginPerformance",
            "expression": "IF([InternetPreviousQuarterMarginProportionToQTD]<>0,([InternetCurrentQuarterMargin]-[InternetPreviousQuarterMarginProportionToQTD])/[InternetPreviousQuarterMarginProportionToQTD],BLANK())",
            "kpi": {
              "targetExpression": "1,25",
              "statusGraphic": "Shapes",
              "statusExpression": [
                "var x='FactInternetSales'[InternetCurrentQuarterMarginPerformance] return",
                "            if(ISBLANK(x),BLANK(),",
                "                    If(x<0.8,-1,",
                "\t                If(x<1.03,0,1)",
                "                )",
                "            )",
                "            "
              ],
              "annotations": [
                {
                  "name": "GoalType",
                  "value": "StaticValue"
                },
                {
                  "name": "KpiStatusType",
                  "value": "Linear"
                },
                {
                  "name": "KpiThresholdType",
                  "value": "Absolute"
                },
                {
                  "name": "KpiThresholdOrdering",
                  "value": "Ascending"
                },
                {
                  "name": "KpiThresholdCount",
                  "value": "2"
                },
                {
                  "name": "KpiThreshold_0",
                  "value": "0.8"
                },
                {
                  "name": "KpiThreshold_1",
                  "value": "1.03"
                }
              ]
            }
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "8738ec9b-a8f2-4340-9faa-241768d47ad9",
        "fromTable": "DimCustomer",
        "fromColumn": "GeographyKey",
        "toTable": "DimGeography",
        "toColumn": "GeographyKey"
      },
      {
        "name": "0b6da1c1-6fbb-4daa-9493-35ee670e19f4",
        "fromTable": "DimProduct",
        "fromColumn": "ProductSubcategoryKey",
        "toTable": "DimProductSubcategory",
        "toColumn": "ProductSubcategoryKey"
      },
      {
        "name": "cf6a9aec-2bed-483f-8c30-0206debc6df5",
        "fromTable": "DimProductSubcategory",
        "fromColumn": "ProductCategoryKey",
        "toTable": "DimProductCategory",
        "toColumn": "ProductCategoryKey"
      },
      {
        "name": "c966759e-2417-4261-9d95-ff40face124a",
        "fromTable": "FactInternetSales",
        "fromColumn": "CustomerKey",
        "toTable": "DimCustomer",
        "toColumn": "CustomerKey"
      },
      {
        "name": "ad60ab6c-43c2-4da1-999b-b382350c58fb",
        "fromTable": "FactInternetSales",
        "fromColumn": "ProductKey",
        "toTable": "DimProduct",
        "toColumn": "ProductKey"
      },
      {
        "name": "ada2a116-5704-41a8-9152-cf388ac51acd",
        "fromTable": "FactInternetSales",
        "fromColumn": "OrderDateKey",
        "toTable": "DimDate",
        "toColumn": "DateKey"
      }
    ],
    "perspectives": [
      {
        "name": "Internet Sales",
        "tables": [
          {
            "name": "DimDate",
            "columns": [
              {
                "name": "CalendarQuarter"
              },
              {
                "name": "CalendarSemester"
              },
              {
                "name": "CalendarYear"
              },
              {
                "name": "Date"
              },
              {
                "name": "DateKey"
              },
              {
                "name": "DayNumberOfMonth"
              },
              {
                "name": "DayNumberOfWeek"
              },
              {
                "name": "DayNumberOfYear"
              },
              {
                "name": "DayOfWeek "
              },
              {
                "name": "EnglishDayNameOfWeek"
              },
              {
                "name": "EnglishMonthName"
              },
              {
                "name": "FiscalQuarter"
              },
              {
                "name": "FiscalSemester"
              },
              {
                "name": "FiscalYear"
              },
              {
                "name": "MonthCalendar"
              },
              {
                "name": "MonthNumberOfYear"
              },
              {
                "name": "WeekNumberOfYear"
              }
            ],
            "measures": [
              {
                "name": "DaysCurrentQuarterToDate"
              },
              {
                "name": "DaysInCurrentQuarter"
              }
            ]
          },
          {
            "name": "DimGeography",
            "columns": [
              {
                "name": "City"
              },
              {
                "name": "CountryRegionCode"
              },
              {
                "name": "EnglishCountryRegionName"
              },
              {
                "name": "GeographyKey"
              },
              {
                "name": "PostalCode"
              },
              {
                "name": "SalesTerritoryKey"
              },
              {
                "name": "StateProvinceCode"
              },
              {
                "name": "StateProvinceName"
              }
            ]
          },
          {
            "name": "DimProduct",
            "columns": [
              {
                "name": "Class"
              },
              {
                "name": "Color"
              },
              {
                "name": "DaysToManufacture"
              },
              {
                "name": "DealerPrice"
              },
              {
                "name": "EndDate"
              },
              {
                "name": "EnglishDescription"
              },
              {
                "name": "EnglishProductName"
              },
              {
                "name": "FinishedGoodsFlag"
              },
              {
                "name": "FrenchProductName"
              },
              {
                "name": "ListPrice"
              },
              {
                "name": "ModelName"
              },
              {
                "name": "ProductAlternateKey"
              },
              {
                "name": "ProductCategoryName"
              },
              {
                "name": "ProductKey"
              },
              {
                "name": "ProductLine"
              },
              {
                "name": "ProductSubcategoryKey"
              },
              {
                "name": "ProductSubcategoryName"
              },
              {
                "name": "ReorderPoint"
              },
              {
                "name": "SafetyStockLevel"
              },
              {
                "name": "Size"
              },
              {
                "name": "SizeRange"
              },
              {
                "name": "SizeUnitMeasureCode"
              },
              {
                "name": "SpanishProductName"
              },
              {
                "name": "StandardCost"
              },
              {
                "name": "StartDate"
              },
              {
                "name": "Status"
              },
              {
                "name": "Style"
              },
              {
                "name": "Weight"
              },
              {
                "name": "WeightUnitMeasureCode"
              }
            ],
            "hierarchies": [
              {
                "name": "Category"
              }
            ]
          },
          {
            "name": "DimProductCategory",
            "columns": [
              {
                "name": "EnglishProductCategoryName"
              },
              {
                "name": "ProductCategoryAlternateKey"
              },
              {
                "name": "ProductCategoryKey"
              }
            ]
          },
          {
            "name": "DimProductSubcategory",
            "columns": [
              {
                "name": "EnglishProductSubcategoryName"
              },
              {
                "name": "ProductCategoryKey"
              },
              {
                "name": "ProductSubcategoryAlternateKey"
              },
              {
                "name": "ProductSubcategoryKey"
              }
            ]
          },
          {
            "name": "FactInternetSales",
            "columns": [
              {
                "name": "CarrierTrackingNumber"
              },
              {
                "name": "CurrencyKey"
              },
              {
                "name": "CustomerKey"
              },
              {
                "name": "CustomerPONumber"
              },
              {
                "name": "DiscountAmount"
              },
              {
                "name": "DueDateKey"
              },
              {
                "name": "ExtendedAmount"
              },
              {
                "name": "Freight"
              },
              {
                "name": "Margin"
              },
              {
                "name": "OrderDateKey"
              },
              {
                "name": "OrderQuantity"
              },
              {
                "name": "ProductKey"
              },
              {
                "name": "ProductStandardCost"
              },
              {
                "name": "PromotionKey"
              },
              {
                "name": "RevisionNumber"
              },
              {
                "name": "SalesAmount"
              },
              {
                "name": "SalesOrderLineNumber"
              },
              {
                "name": "SalesOrderNumber"
              },
              {
                "name": "SalesTerritoryKey"
              },
              {
                "name": "ShipDateKey"
              },
              {
                "name": "TaxAmt"
              },
              {
                "name": "TotalProductCost"
              },
              {
                "name": "UnitPrice"
              },
              {
                "name": "UnitPriceDiscountPct"
              }
            ],
            "measures": [
              {
                "name": "InternetCurrentQuarterMargin"
              },
              {
                "name": "InternetCurrentQuarterSales"
              },
              {
                "name": "InternetDistinctCountSalesOrder"
              },
              {
                "name": "InternetOrderLinesCount"
              },
              {
                "name": "InternetPreviousQuarterMargin"
              },
              {
                "name": "InternetPreviousQuarterMarginProportionToQTD"
              },
              {
                "name": "InternetPreviousQuarterSales"
              },
              {
                "name": "InternetPreviousQuarterSalesProportionToQTD"
              },
              {
                "name": "InternetTotalDiscountAmount"
              },
              {
                "name": "InternetTotalFreight"
              },
              {
                "name": "InternetTotalMargin"
              },
              {
                "name": "InternetTotalProductCost"
              },
              {
                "name": "InternetTotalSales"
              },
              {
                "name": "InternetTotalTaxAmt"
              },
              {
                "name": "InternetTotalUnits"
              },
              {
                "name": "InternetCurrentQuarterMarginPerformance"
              },
              {
                "name": "InternetCurrentQuarterSalesPerformance"
              }
            ]
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "600"
      }
    ]
  },
  "id": "SemanticModel"
}